# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test

build_fe_borrower_project:
  stage: test
  image: node:22.12.2
  cache:
    paths:
      - node_modules/
  before_script:
    - source ~/.profile
    - source ~/.bashrc
    - export PATH="$PATH:~/.nvm/versions/node/v22.12.2/bin"
  script:
    - cd ./plsh-fe-borrower
    - yarn install
    - npm run build
  only:
    - merge_requests
    - client/borrower/develop


build_fe_librarian_project:
  stage: test
  image: node:22.12.2
  cache:
    paths:
      - node_modules/
  before_script:
    - source ~/.profile
    - source ~/.bashrc
    - export PATH="$PATH:~/.nvm/versions/node/v22.12.2/bin"
  script:
    - cd ./plsh-fe-librarian
    - yarn install
    - npm run build
  only:
    - merge_requests
    - client/librarian/develop
